// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canned_responses.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCannedResponse = `-- name: CreateCannedResponse :one
INSERT INTO canned_responses (name, content)
VALUES ($1, $2)
RETURNING id, name, content, created_at, updated_at
`

type CreateCannedResponseParams struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

func (q *Queries) CreateCannedResponse(ctx context.Context, arg CreateCannedResponseParams) (CannedResponse, error) {
	row := q.db.QueryRowContext(ctx, createCannedResponse, arg.Name, arg.Content)
	var i CannedResponse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCannedResponse = `-- name: DeleteCannedResponse :exec
DELETE FROM canned_responses
WHERE id = $1
`

func (q *Queries) DeleteCannedResponse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCannedResponse, id)
	return err
}

const getCannedResponse = `-- name: GetCannedResponse :one
SELECT id, name, content, created_at, updated_at FROM canned_responses
WHERE id = $1
`

func (q *Queries) GetCannedResponse(ctx context.Context, id uuid.UUID) (CannedResponse, error) {
	row := q.db.QueryRowContext(ctx, getCannedResponse, id)
	var i CannedResponse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCannedResponseByName = `-- name: GetCannedResponseByName :one
SELECT id, name, content, created_at, updated_at FROM canned_responses
WHERE name = $1
`

func (q *Queries) GetCannedResponseByName(ctx context.Context, name string) (CannedResponse, error) {
	row := q.db.QueryRowContext(ctx, getCannedResponseByName, name)
	var i CannedResponse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCannedResponses = `-- name: ListCannedResponses :many
SELECT id, name, content, created_at, updated_at FROM canned_responses
ORDER BY name ASC
`

func (q *Queries) ListCannedResponses(ctx context.Context) ([]CannedResponse, error) {
	rows, err := q.db.QueryContext(ctx, listCannedResponses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CannedResponse
	for rows.Next() {
		var i CannedResponse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCannedResponse = `-- name: UpdateCannedResponse :one
UPDATE canned_responses
SET name = $2, content = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, content, created_at, updated_at
`

type UpdateCannedResponseParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateCannedResponse(ctx context.Context, arg UpdateCannedResponseParams) (CannedResponse, error) {
	row := q.db.QueryRowContext(ctx, updateCannedResponse, arg.ID, arg.Name, arg.Content)
	var i CannedResponse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
