// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: itsm.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const deleteDefaultTicketType = `-- name: DeleteDefaultTicketType :exec
DELETE FROM cti_default_ticket_types
WHERE category_id = $1
  AND type_id  = COALESCE($2, '00000000-0000-0000-0000-000000000000'::uuid)
  AND item_id  = COALESCE($3, '00000000-0000-0000-0000-000000000000'::uuid)
`

type DeleteDefaultTicketTypeParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	TypeID     uuid.UUID `json:"type_id"`
	ItemID     uuid.UUID `json:"item_id"`
}

func (q *Queries) DeleteDefaultTicketType(ctx context.Context, arg DeleteDefaultTicketTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteDefaultTicketType, arg.CategoryID, arg.TypeID, arg.ItemID)
	return err
}

const getDefaultTicketType = `-- name: GetDefaultTicketType :one
SELECT ticket_type FROM cti_default_ticket_types
WHERE category_id = $1
  AND type_id  = COALESCE($2, '00000000-0000-0000-0000-000000000000'::uuid)
  AND item_id  = COALESCE($3, '00000000-0000-0000-0000-000000000000'::uuid)
LIMIT 1
`

type GetDefaultTicketTypeParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	TypeID     uuid.UUID `json:"type_id"`
	ItemID     uuid.UUID `json:"item_id"`
}

// Hierarchical lookup: item → type → category → no row.
// Uses sentinel UUID '00000000-...' for missing type_id / item_id.
func (q *Queries) GetDefaultTicketType(ctx context.Context, arg GetDefaultTicketTypeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getDefaultTicketType, arg.CategoryID, arg.TypeID, arg.ItemID)
	var ticket_type string
	err := row.Scan(&ticket_type)
	return ticket_type, err
}

const listDefaultTicketTypes = `-- name: ListDefaultTicketTypes :many
SELECT
    category_id,
    CASE WHEN type_id = '00000000-0000-0000-0000-000000000000' THEN NULL ELSE type_id END AS type_id,
    CASE WHEN item_id = '00000000-0000-0000-0000-000000000000' THEN NULL ELSE item_id END AS item_id,
    ticket_type
FROM cti_default_ticket_types
ORDER BY category_id, type_id, item_id
`

type ListDefaultTicketTypesRow struct {
	CategoryID uuid.UUID   `json:"category_id"`
	TypeID     interface{} `json:"type_id"`
	ItemID     interface{} `json:"item_id"`
	TicketType string      `json:"ticket_type"`
}

func (q *Queries) ListDefaultTicketTypes(ctx context.Context) ([]ListDefaultTicketTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDefaultTicketTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDefaultTicketTypesRow
	for rows.Next() {
		var i ListDefaultTicketTypesRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.TicketType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDefaultTicketType = `-- name: UpsertDefaultTicketType :exec
INSERT INTO cti_default_ticket_types (category_id, type_id, item_id, ticket_type)
VALUES (
    $1,
    COALESCE($2, '00000000-0000-0000-0000-000000000000'::uuid),
    COALESCE($3, '00000000-0000-0000-0000-000000000000'::uuid),
    $4
)
ON CONFLICT (category_id, type_id, item_id)
DO UPDATE SET ticket_type = EXCLUDED.ticket_type
`

type UpsertDefaultTicketTypeParams struct {
	CategoryID uuid.UUID   `json:"category_id"`
	Column2    interface{} `json:"column_2"`
	Column3    interface{} `json:"column_3"`
	TicketType string      `json:"ticket_type"`
}

func (q *Queries) UpsertDefaultTicketType(ctx context.Context, arg UpsertDefaultTicketTypeParams) error {
	_, err := q.db.ExecContext(ctx, upsertDefaultTicketType,
		arg.CategoryID,
		arg.Column2,
		arg.Column3,
		arg.TicketType,
	)
	return err
}
