// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kb.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
)

const createKBArticle = `-- name: CreateKBArticle :one
INSERT INTO kb_articles (category_id, title, content, status)
VALUES ($1, $2, $3, $4)
RETURNING id, category_id, title, content, status, views, created_at, updated_at, tsv, embedding
`

type CreateKBArticleParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateKBArticle(ctx context.Context, arg CreateKBArticleParams) (KbArticle, error) {
	row := q.db.QueryRowContext(ctx, createKBArticle,
		arg.CategoryID,
		arg.Title,
		arg.Content,
		arg.Status,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tsv,
		&i.Embedding,
	)
	return i, err
}

const createKBCategory = `-- name: CreateKBCategory :one
INSERT INTO kb_categories (name, description, is_public)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_public, created_at, updated_at
`

type CreateKBCategoryParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsPublic    bool           `json:"is_public"`
}

func (q *Queries) CreateKBCategory(ctx context.Context, arg CreateKBCategoryParams) (KbCategory, error) {
	row := q.db.QueryRowContext(ctx, createKBCategory, arg.Name, arg.Description, arg.IsPublic)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKBArticle = `-- name: DeleteKBArticle :exec
DELETE FROM kb_articles
WHERE id = $1
`

func (q *Queries) DeleteKBArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteKBArticle, id)
	return err
}

const deleteKBCategory = `-- name: DeleteKBCategory :exec
DELETE FROM kb_categories
WHERE id = $1
`

func (q *Queries) DeleteKBCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteKBCategory, id)
	return err
}

const getKBArticle = `-- name: GetKBArticle :one
SELECT id, category_id, title, content, status, views, created_at, updated_at, tsv, embedding FROM kb_articles
WHERE id = $1
`

func (q *Queries) GetKBArticle(ctx context.Context, id uuid.UUID) (KbArticle, error) {
	row := q.db.QueryRowContext(ctx, getKBArticle, id)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tsv,
		&i.Embedding,
	)
	return i, err
}

const getKBCategory = `-- name: GetKBCategory :one
SELECT id, name, description, is_public, created_at, updated_at FROM kb_categories
WHERE id = $1
`

func (q *Queries) GetKBCategory(ctx context.Context, id uuid.UUID) (KbCategory, error) {
	row := q.db.QueryRowContext(ctx, getKBCategory, id)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKBCategoryByName = `-- name: GetKBCategoryByName :one
SELECT id, name, description, is_public, created_at, updated_at FROM kb_categories
WHERE name = $1
`

func (q *Queries) GetKBCategoryByName(ctx context.Context, name string) (KbCategory, error) {
	row := q.db.QueryRowContext(ctx, getKBCategoryByName, name)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimilarKBArticles = `-- name: GetSimilarKBArticles :many
SELECT id, category_id, title, content, status, views, created_at, updated_at,
       (embedding <=> $1)::float4 as distance
FROM kb_articles
WHERE status = 'published' AND embedding IS NOT NULL
ORDER BY embedding <=> $1
LIMIT $2
`

type GetSimilarKBArticlesParams struct {
	Embedding interface{} `json:"embedding"`
	Limit     int32       `json:"limit"`
}

type GetSimilarKBArticlesRow struct {
	ID         uuid.UUID `json:"id"`
	CategoryID uuid.UUID `json:"category_id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	Status     string    `json:"status"`
	Views      int32     `json:"views"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Distance   float32   `json:"distance"`
}

func (q *Queries) GetSimilarKBArticles(ctx context.Context, arg GetSimilarKBArticlesParams) ([]GetSimilarKBArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSimilarKBArticles, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimilarKBArticlesRow
	for rows.Next() {
		var i GetSimilarKBArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.Views,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementKBArticleViews = `-- name: IncrementKBArticleViews :exec
UPDATE kb_articles
SET views = views + 1
WHERE id = $1
`

func (q *Queries) IncrementKBArticleViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementKBArticleViews, id)
	return err
}

const listKBArticles = `-- name: ListKBArticles :many
SELECT id, category_id, title, content, status, views, created_at, updated_at, tsv, embedding FROM kb_articles
ORDER BY created_at DESC
`

func (q *Queries) ListKBArticles(ctx context.Context) ([]KbArticle, error) {
	rows, err := q.db.QueryContext(ctx, listKBArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbArticle
	for rows.Next() {
		var i KbArticle
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.Views,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tsv,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBArticlesByCategory = `-- name: ListKBArticlesByCategory :many
SELECT id, category_id, title, content, status, views, created_at, updated_at, tsv, embedding FROM kb_articles
WHERE category_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListKBArticlesByCategory(ctx context.Context, categoryID uuid.UUID) ([]KbArticle, error) {
	rows, err := q.db.QueryContext(ctx, listKBArticlesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbArticle
	for rows.Next() {
		var i KbArticle
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.Views,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tsv,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBCategories = `-- name: ListKBCategories :many
SELECT id, name, description, is_public, created_at, updated_at FROM kb_categories
ORDER BY name ASC
`

func (q *Queries) ListKBCategories(ctx context.Context) ([]KbCategory, error) {
	rows, err := q.db.QueryContext(ctx, listKBCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbCategory
	for rows.Next() {
		var i KbCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKBArticlesAll = `-- name: SearchKBArticlesAll :many
SELECT id, category_id, title, content, status, views, created_at, updated_at, tsv, embedding FROM kb_articles
WHERE tsv @@ websearch_to_tsquery('simple', $1)
ORDER BY created_at DESC
`

func (q *Queries) SearchKBArticlesAll(ctx context.Context, websearchToTsquery string) ([]KbArticle, error) {
	rows, err := q.db.QueryContext(ctx, searchKBArticlesAll, websearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbArticle
	for rows.Next() {
		var i KbArticle
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.Views,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tsv,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKBArticlesPublic = `-- name: SearchKBArticlesPublic :many
SELECT a.id, a.category_id, a.title, a.content, a.status, a.views, a.created_at, a.updated_at, a.tsv, a.embedding FROM kb_articles a
JOIN kb_categories c ON a.category_id = c.id
WHERE c.is_public = true AND a.status = 'published'
  AND a.tsv @@ websearch_to_tsquery('simple', $1)
ORDER BY a.created_at DESC
`

func (q *Queries) SearchKBArticlesPublic(ctx context.Context, websearchToTsquery string) ([]KbArticle, error) {
	rows, err := q.db.QueryContext(ctx, searchKBArticlesPublic, websearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbArticle
	for rows.Next() {
		var i KbArticle
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.Views,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tsv,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKBArticle = `-- name: UpdateKBArticle :one
UPDATE kb_articles
SET category_id = $2, title = $3, content = $4, status = $5, updated_at = now()
WHERE id = $1
RETURNING id, category_id, title, content, status, views, created_at, updated_at, tsv, embedding
`

type UpdateKBArticleParams struct {
	ID         uuid.UUID `json:"id"`
	CategoryID uuid.UUID `json:"category_id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	Status     string    `json:"status"`
}

func (q *Queries) UpdateKBArticle(ctx context.Context, arg UpdateKBArticleParams) (KbArticle, error) {
	row := q.db.QueryRowContext(ctx, updateKBArticle,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.Content,
		arg.Status,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tsv,
		&i.Embedding,
	)
	return i, err
}

const updateKBArticleEmbedding = `-- name: UpdateKBArticleEmbedding :exec
UPDATE kb_articles
SET embedding = $2, updated_at = now()
WHERE id = $1
`

type UpdateKBArticleEmbeddingParams struct {
	ID        uuid.UUID   `json:"id"`
	Embedding interface{} `json:"embedding"`
}

func (q *Queries) UpdateKBArticleEmbedding(ctx context.Context, arg UpdateKBArticleEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, updateKBArticleEmbedding, arg.ID, arg.Embedding)
	return err
}

const updateKBCategory = `-- name: UpdateKBCategory :one
UPDATE kb_categories
SET name = $2, description = $3, is_public = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_public, created_at, updated_at
`

type UpdateKBCategoryParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsPublic    bool           `json:"is_public"`
}

func (q *Queries) UpdateKBCategory(ctx context.Context, arg UpdateKBCategoryParams) (KbCategory, error) {
	row := q.db.QueryRowContext(ctx, updateKBCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
