// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: kb.sql

package dbgen

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
)

const createKBArticle = `-- name: CreateKBArticle :one
INSERT INTO kb_articles (category_id, title, content, status)
VALUES ($1, $2, $3, $4)
RETURNING id, category_id, title, content, status, views, created_at, updated_at
`

type CreateKBArticleParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateKBArticle(ctx context.Context, arg CreateKBArticleParams) (KbArticle, error) {
	row := q.db.QueryRowContext(ctx, createKBArticle,
		arg.CategoryID,
		arg.Title,
		arg.Content,
		arg.Status,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKBCategory = `-- name: CreateKBCategory :one
INSERT INTO kb_categories (name, description, is_public)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_public, created_at, updated_at
`

type CreateKBCategoryParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsPublic    bool           `json:"is_public"`
}

func (q *Queries) CreateKBCategory(ctx context.Context, arg CreateKBCategoryParams) (KbCategory, error) {
	row := q.db.QueryRowContext(ctx, createKBCategory, arg.Name, arg.Description, arg.IsPublic)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKBArticle = `-- name: DeleteKBArticle :exec
DELETE FROM kb_articles
WHERE id = $1
`

func (q *Queries) DeleteKBArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteKBArticle, id)
	return err
}

const deleteKBCategory = `-- name: DeleteKBCategory :exec
DELETE FROM kb_categories
WHERE id = $1
`

func (q *Queries) DeleteKBCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteKBCategory, id)
	return err
}

const getKBArticle = `-- name: GetKBArticle :one
SELECT id, category_id, title, content, status, views, created_at, updated_at FROM kb_articles
WHERE id = $1
`

func (q *Queries) GetKBArticle(ctx context.Context, id uuid.UUID) (KbArticle, error) {
	row := q.db.QueryRowContext(ctx, getKBArticle, id)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKBCategory = `-- name: GetKBCategory :one
SELECT id, name, description, is_public, created_at, updated_at FROM kb_categories
WHERE id = $1
`

func (q *Queries) GetKBCategory(ctx context.Context, id uuid.UUID) (KbCategory, error) {
	row := q.db.QueryRowContext(ctx, getKBCategory, id)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKBCategoryByName = `-- name: GetKBCategoryByName :one
SELECT id, name, description, is_public, created_at, updated_at FROM kb_categories
WHERE name = $1
`

func (q *Queries) GetKBCategoryByName(ctx context.Context, name string) (KbCategory, error) {
	row := q.db.QueryRowContext(ctx, getKBCategoryByName, name)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementKBArticleViews = `-- name: IncrementKBArticleViews :exec
UPDATE kb_articles
SET views = views + 1
WHERE id = $1
`

func (q *Queries) IncrementKBArticleViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementKBArticleViews, id)
	return err
}

const listKBArticles = `-- name: ListKBArticles :many
SELECT id, category_id, title, content, status, views, created_at, updated_at FROM kb_articles
ORDER BY created_at DESC
`

func (q *Queries) ListKBArticles(ctx context.Context) ([]KbArticle, error) {
	rows, err := q.db.QueryContext(ctx, listKBArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbArticle
	for rows.Next() {
		var i KbArticle
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.Views,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBArticlesByCategory = `-- name: ListKBArticlesByCategory :many
SELECT id, category_id, title, content, status, views, created_at, updated_at FROM kb_articles
WHERE category_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListKBArticlesByCategory(ctx context.Context, categoryID uuid.UUID) ([]KbArticle, error) {
	rows, err := q.db.QueryContext(ctx, listKBArticlesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbArticle
	for rows.Next() {
		var i KbArticle
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.Views,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBCategories = `-- name: ListKBCategories :many
SELECT id, name, description, is_public, created_at, updated_at FROM kb_categories
ORDER BY name ASC
`

func (q *Queries) ListKBCategories(ctx context.Context) ([]KbCategory, error) {
	rows, err := q.db.QueryContext(ctx, listKBCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbCategory
	for rows.Next() {
		var i KbCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKBArticle = `-- name: UpdateKBArticle :one
UPDATE kb_articles
SET category_id = $2, title = $3, content = $4, status = $5, updated_at = now()
WHERE id = $1
RETURNING id, category_id, title, content, status, views, created_at, updated_at
`

type UpdateKBArticleParams struct {
	ID         uuid.UUID `json:"id"`
	CategoryID uuid.UUID `json:"category_id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	Status     string    `json:"status"`
}

func (q *Queries) UpdateKBArticle(ctx context.Context, arg UpdateKBArticleParams) (KbArticle, error) {
	row := q.db.QueryRowContext(ctx, updateKBArticle,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.Content,
		arg.Status,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKBCategory = `-- name: UpdateKBCategory :one
UPDATE kb_categories
SET name = $2, description = $3, is_public = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_public, created_at, updated_at
`

type UpdateKBCategoryParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsPublic    bool           `json:"is_public"`
}

func (q *Queries) UpdateKBCategory(ctx context.Context, arg UpdateKBCategoryParams) (KbCategory, error) {
	row := q.db.QueryRowContext(ctx, updateKBCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i KbCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
