// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"

	uuid "github.com/google/uuid"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	AddGroupScope(ctx context.Context, arg AddGroupScopeParams) error
	AddTicketTag(ctx context.Context, arg AddTicketTagParams) error
	AdminSetPassword(ctx context.Context, arg AdminSetPasswordParams) error
	ClearMFA(ctx context.Context, id uuid.UUID) error
	CountTicketsByStatus(ctx context.Context, statusID uuid.UUID) (int64, error)
	CountTicketsByStatusForAssignee(ctx context.Context, arg CountTicketsByStatusForAssigneeParams) (int64, error)
	CountTicketsByStatusForReporter(ctx context.Context, arg CountTicketsByStatusForReporterParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error
	CreateCannedResponse(ctx context.Context, arg CreateCannedResponseParams) (CannedResponse, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	// ── Assignments ───────────────────────────────────────────────────────────────
	CreateCustomFieldAssignment(ctx context.Context, arg CreateCustomFieldAssignmentParams) (CustomFieldAssignment, error)
	// ── Field definitions ─────────────────────────────────────────────────────────
	CreateCustomFieldDef(ctx context.Context, arg CreateCustomFieldDefParams) (CustomFieldDef, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	CreateItem(ctx context.Context, arg CreateItemParams) error
	CreateKBArticle(ctx context.Context, arg CreateKBArticleParams) (KbArticle, error)
	CreateKBCategory(ctx context.Context, arg CreateKBCategoryParams) (KbCategory, error)
	CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error
	CreatePlugin(ctx context.Context, arg CreatePluginParams) error
	CreateReply(ctx context.Context, arg CreateReplyParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateSLAPolicy(ctx context.Context, arg CreateSLAPolicyParams) error
	CreateSLARecord(ctx context.Context, arg CreateSLARecordParams) error
	CreateStatus(ctx context.Context, arg CreateStatusParams) error
	CreateStatusHistoryEntry(ctx context.Context, arg CreateStatusHistoryEntryParams) error
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) error
	CreateTicketLink(ctx context.Context, arg CreateTicketLinkParams) error
	CreateType(ctx context.Context, arg CreateTypeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateWebhookConfig(ctx context.Context, arg CreateWebhookConfigParams) error
	CreateWhatsAppSession(ctx context.Context, arg CreateWhatsAppSessionParams) error
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteAttachment(ctx context.Context, id uuid.UUID) error
	DeleteCannedResponse(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteCustomFieldAssignment(ctx context.Context, id uuid.UUID) error
	DeleteCustomFieldValue(ctx context.Context, arg DeleteCustomFieldValueParams) error
	DeleteDefaultTicketType(ctx context.Context, arg DeleteDefaultTicketTypeParams) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteItem(ctx context.Context, id uuid.UUID) error
	DeleteKBArticle(ctx context.Context, id uuid.UUID) error
	DeleteKBCategory(ctx context.Context, id uuid.UUID) error
	DeleteOAuthClient(ctx context.Context, id uuid.UUID) error
	DeletePendingRegistration(ctx context.Context, id uuid.UUID) error
	DeletePlugin(ctx context.Context, id string) error
	DeleteRole(ctx context.Context, name string) error
	DeleteSLAPolicy(ctx context.Context, id uuid.UUID) error
	DeleteStatus(ctx context.Context, id uuid.UUID) error
	DeleteTicketLink(ctx context.Context, arg DeleteTicketLinkParams) error
	DeleteType(ctx context.Context, id uuid.UUID) error
	DeleteWebhookConfig(ctx context.Context, id uuid.UUID) error
	DeleteWhatsAppSession(ctx context.Context, phone string) error
	DisableUser(ctx context.Context, id uuid.UUID) error
	EnableUser(ctx context.Context, id uuid.UUID) error
	// Category-specific policy takes precedence over a global one (category_id IS NULL).
	FindSLAPolicy(ctx context.Context, arg FindSLAPolicyParams) (SlaPolicy, error)
	GetAPIKeyByHash(ctx context.Context, hashedToken string) (ApiKey, error)
	GetActiveTicketByWhatsApp(ctx context.Context, whatsappPhone sql.NullString) (Ticket, error)
	GetAgentCSATPerformance(ctx context.Context) ([]GetAgentCSATPerformanceRow, error)
	GetAttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error)
	GetCSATDistribution(ctx context.Context, arg GetCSATDistributionParams) ([]GetCSATDistributionRow, error)
	GetCannedResponse(ctx context.Context, id uuid.UUID) (CannedResponse, error)
	GetCannedResponseByName(ctx context.Context, name string) (CannedResponse, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetCustomFieldAssignment(ctx context.Context, id uuid.UUID) (CustomFieldAssignment, error)
	GetCustomFieldDef(ctx context.Context, id uuid.UUID) (CustomFieldDef, error)
	// Hierarchical lookup: item → type → category → no row.
	// Uses sentinel UUID '00000000-...' for missing type_id / item_id.
	GetDefaultTicketType(ctx context.Context, arg GetDefaultTicketTypeParams) (string, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetItem(ctx context.Context, id uuid.UUID) (Item, error)
	GetKBArticle(ctx context.Context, id uuid.UUID) (KbArticle, error)
	GetKBCategory(ctx context.Context, id uuid.UUID) (KbCategory, error)
	GetKBCategoryByName(ctx context.Context, name string) (KbCategory, error)
	GetLatestTicketByWhatsApp(ctx context.Context, whatsappPhone sql.NullString) (Ticket, error)
	GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error)
	GetOverallCSAT(ctx context.Context, arg GetOverallCSATParams) (GetOverallCSATRow, error)
	GetPendingRegistrationByToken(ctx context.Context, token uuid.UUID) (PendingRegistration, error)
	GetPlugin(ctx context.Context, id string) (Plugin, error)
	GetRecentCSATComments(ctx context.Context, arg GetRecentCSATCommentsParams) ([]GetRecentCSATCommentsRow, error)
	GetReplyByExternalID(ctx context.Context, externalMessageID sql.NullString) (TicketReply, error)
	GetRole(ctx context.Context, name string) (Role, error)
	GetSLAPolicy(ctx context.Context, id uuid.UUID) (SlaPolicy, error)
	GetSLARecord(ctx context.Context, ticketID uuid.UUID) (SlaRecord, error)
	GetSetting(ctx context.Context, key string) (json.RawMessage, error)
	GetStatus(ctx context.Context, id uuid.UUID) (Status, error)
	GetStatusByName(ctx context.Context, name string) (Status, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error)
	GetTicketByTrackingNumber(ctx context.Context, trackingNumber string) (Ticket, error)
	GetType(ctx context.Context, id uuid.UUID) (Type, error)
	GetUnratedTicketByWhatsApp(ctx context.Context, whatsappPhone sql.NullString) (Ticket, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIDAdmin(ctx context.Context, id uuid.UUID) (User, error)
	GetUserBySAMLSubject(ctx context.Context, samlSubject string) (User, error)
	GetWebhookConfig(ctx context.Context, id uuid.UUID) (WebhookConfig, error)
	GetWhatsAppSession(ctx context.Context, phone string) (GetWhatsAppSessionRow, error)
	IncrementKBArticleViews(ctx context.Context, id uuid.UUID) error
	ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListActiveTags(ctx context.Context) ([]Tag, error)
	ListAllTags(ctx context.Context) ([]Tag, error)
	ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error)
	ListAssignmentsForScope(ctx context.Context, arg ListAssignmentsForScopeParams) ([]ListAssignmentsForScopeRow, error)
	ListAttachments(ctx context.Context, ticketID uuid.UUID) ([]Attachment, error)
	ListAuditByEntity(ctx context.Context, arg ListAuditByEntityParams) ([]AuditLog, error)
	ListCannedResponses(ctx context.Context) ([]CannedResponse, error)
	ListCategories(ctx context.Context, dollar_1 bool) ([]Category, error)
	ListCustomFieldDefs(ctx context.Context) ([]CustomFieldDef, error)
	ListCustomFieldValuesForTicket(ctx context.Context, ticketID uuid.UUID) ([]ListCustomFieldValuesForTicketRow, error)
	ListDefaultTicketTypes(ctx context.Context) ([]ListDefaultTicketTypesRow, error)
	ListEnabledWebhookConfigs(ctx context.Context) ([]WebhookConfig, error)
	ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error)
	ListGroupScopes(ctx context.Context, groupID uuid.UUID) ([]GroupScope, error)
	ListGroups(ctx context.Context) ([]Group, error)
	// Returns only groups with exactly this scope (null type = category-level, non-null = type-specific).
	ListGroupsForExactScope(ctx context.Context, arg ListGroupsForExactScopeParams) ([]Group, error)
	ListGroupsForUser(ctx context.Context, userID uuid.UUID) ([]Group, error)
	ListGroupsInScope(ctx context.Context, arg ListGroupsInScopeParams) ([]Group, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	ListKBArticles(ctx context.Context) ([]KbArticle, error)
	ListKBArticlesByCategory(ctx context.Context, categoryID uuid.UUID) ([]KbArticle, error)
	ListKBCategories(ctx context.Context) ([]KbCategory, error)
	ListOAuthClients(ctx context.Context) ([]OauthClient, error)
	ListPlugins(ctx context.Context) ([]Plugin, error)
	ListReplies(ctx context.Context, ticketID uuid.UUID) ([]ListRepliesRow, error)
	ListResolvedTicketsBefore(ctx context.Context, arg ListResolvedTicketsBeforeParams) ([]Ticket, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListSLAPolicies(ctx context.Context) ([]SlaPolicy, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListStatuses(ctx context.Context) ([]Status, error)
	ListTicketLinks(ctx context.Context, sourceTicketID uuid.UUID) ([]TicketLink, error)
	ListTicketStatusHistory(ctx context.Context, ticketID uuid.UUID) ([]ListTicketStatusHistoryRow, error)
	ListTicketTags(ctx context.Context, ticketID uuid.UUID) ([]Tag, error)
	ListTicketsByAssigneeGroup(ctx context.Context, arg ListTicketsByAssigneeGroupParams) ([]Ticket, error)
	ListTicketsByAssigneeUser(ctx context.Context, arg ListTicketsByAssigneeUserParams) ([]Ticket, error)
	ListTicketsByReporter(ctx context.Context, arg ListTicketsByReporterParams) ([]Ticket, error)
	ListTicketsByStatus(ctx context.Context, arg ListTicketsByStatusParams) ([]Ticket, error)
	ListTypes(ctx context.Context, arg ListTypesParams) ([]Type, error)
	ListUnassignedTickets(ctx context.Context, arg ListUnassignedTicketsParams) ([]Ticket, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]User, error)
	NextTicketSeq(ctx context.Context) (int64, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	RemoveGroupScope(ctx context.Context, arg RemoveGroupScopeParams) error
	RemoveTicketTag(ctx context.Context, arg RemoveTicketTagParams) error
	RestoreTag(ctx context.Context, id uuid.UUID) error
	RestoreUser(ctx context.Context, id uuid.UUID) error
	SearchActiveTags(ctx context.Context, name string) ([]Tag, error)
	SearchAllTickets(ctx context.Context, arg SearchAllTicketsParams) ([]Ticket, error)
	SearchKBArticlesAll(ctx context.Context, websearchToTsquery string) ([]KbArticle, error)
	SearchKBArticlesPublic(ctx context.Context, websearchToTsquery string) ([]KbArticle, error)
	SearchTicketsByAssigneeGroup(ctx context.Context, arg SearchTicketsByAssigneeGroupParams) ([]Ticket, error)
	SearchTicketsByAssigneeUser(ctx context.Context, arg SearchTicketsByAssigneeUserParams) ([]Ticket, error)
	SearchTicketsByReporter(ctx context.Context, arg SearchTicketsByReporterParams) ([]Ticket, error)
	SearchUnassignedTickets(ctx context.Context, arg SearchUnassignedTicketsParams) ([]Ticket, error)
	SetSetting(ctx context.Context, arg SetSettingParams) error
	SoftDeleteTag(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error
	UpdateCannedResponse(ctx context.Context, arg UpdateCannedResponseParams) (CannedResponse, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateCustomFieldAssignment(ctx context.Context, arg UpdateCustomFieldAssignmentParams) error
	UpdateCustomFieldDef(ctx context.Context, arg UpdateCustomFieldDefParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
	UpdateItem(ctx context.Context, arg UpdateItemParams) error
	UpdateKBArticle(ctx context.Context, arg UpdateKBArticleParams) (KbArticle, error)
	UpdateKBCategory(ctx context.Context, arg UpdateKBCategoryParams) (KbCategory, error)
	UpdatePlugin(ctx context.Context, arg UpdatePluginParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateSLAPolicy(ctx context.Context, arg UpdateSLAPolicyParams) error
	UpdateSLARecord(ctx context.Context, arg UpdateSLARecordParams) error
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) error
	UpdateTicketCTI(ctx context.Context, arg UpdateTicketCTIParams) error
	UpdateTicketRating(ctx context.Context, arg UpdateTicketRatingParams) error
	UpdateType(ctx context.Context, arg UpdateTypeParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWebhookConfig(ctx context.Context, arg UpdateWebhookConfigParams) error
	// ── Values ────────────────────────────────────────────────────────────────────
	UpsertCustomFieldValue(ctx context.Context, arg UpsertCustomFieldValueParams) error
	UpsertDefaultTicketType(ctx context.Context, arg UpsertDefaultTicketTypeParams) error
	UpsertPendingRegistration(ctx context.Context, arg UpsertPendingRegistrationParams) (PendingRegistration, error)
	UserUpdateAvatar(ctx context.Context, arg UserUpdateAvatarParams) error
}

var _ Querier = (*Queries)(nil)
