// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package dbgen

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
)

const getAgentCSATPerformance = `-- name: GetAgentCSATPerformance :many
SELECT 
    u.id as user_id, 
    u.display_name as user_name, 
    u.email as user_email,
    COUNT(t.id)::int as rated_tickets_count, 
    COALESCE(AVG(t.rating)::float, 0.0)::float as csat_average
FROM tickets t
JOIN users u ON t.assignee_user_id = u.id
WHERE t.rating IS NOT NULL
GROUP BY u.id, u.display_name, u.email
ORDER BY csat_average DESC, rated_tickets_count DESC
`

type GetAgentCSATPerformanceRow struct {
	UserID            uuid.UUID `json:"user_id"`
	UserName          string    `json:"user_name"`
	UserEmail         string    `json:"user_email"`
	RatedTicketsCount int32     `json:"rated_tickets_count"`
	CsatAverage       float64   `json:"csat_average"`
}

func (q *Queries) GetAgentCSATPerformance(ctx context.Context) ([]GetAgentCSATPerformanceRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentCSATPerformance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentCSATPerformanceRow
	for rows.Next() {
		var i GetAgentCSATPerformanceRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.RatedTicketsCount,
			&i.CsatAverage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCSATDistribution = `-- name: GetCSATDistribution :many
SELECT 
    rating::int as rating, 
    COUNT(*)::int as count 
FROM tickets 
WHERE rating IS NOT NULL 
  AND ($1::uuid IS NULL OR assignee_user_id = $1)
  AND ($2::uuid IS NULL OR reporter_user_id = $2)
GROUP BY rating
ORDER BY rating
`

type GetCSATDistributionParams struct {
	AssigneeUserID uuid.NullUUID `json:"assignee_user_id"`
	ReporterUserID uuid.NullUUID `json:"reporter_user_id"`
}

type GetCSATDistributionRow struct {
	Rating int32 `json:"rating"`
	Count  int32 `json:"count"`
}

func (q *Queries) GetCSATDistribution(ctx context.Context, arg GetCSATDistributionParams) ([]GetCSATDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, getCSATDistribution, arg.AssigneeUserID, arg.ReporterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCSATDistributionRow
	for rows.Next() {
		var i GetCSATDistributionRow
		if err := rows.Scan(&i.Rating, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverallCSAT = `-- name: GetOverallCSAT :one
SELECT 
    COALESCE(AVG(rating)::float, 0.0)::float as csat_average, 
    COUNT(*)::int as rated_tickets_count 
FROM tickets 
WHERE rating IS NOT NULL
  AND ($1::uuid IS NULL OR assignee_user_id = $1)
  AND ($2::uuid IS NULL OR reporter_user_id = $2)
`

type GetOverallCSATParams struct {
	AssigneeUserID uuid.NullUUID `json:"assignee_user_id"`
	ReporterUserID uuid.NullUUID `json:"reporter_user_id"`
}

type GetOverallCSATRow struct {
	CsatAverage       float64 `json:"csat_average"`
	RatedTicketsCount int32   `json:"rated_tickets_count"`
}

func (q *Queries) GetOverallCSAT(ctx context.Context, arg GetOverallCSATParams) (GetOverallCSATRow, error) {
	row := q.db.QueryRowContext(ctx, getOverallCSAT, arg.AssigneeUserID, arg.ReporterUserID)
	var i GetOverallCSATRow
	err := row.Scan(&i.CsatAverage, &i.RatedTicketsCount)
	return i, err
}

const getRecentCSATComments = `-- name: GetRecentCSATComments :many
SELECT 
    t.id, 
    t.rating::int as rating, 
    t.rating_comment::text as rating_comment, 
    t.rated_at, 
    u.display_name as assignee_name
FROM tickets t
LEFT JOIN users u ON t.assignee_user_id = u.id
WHERE t.rating IS NOT NULL 
  AND t.rating_comment IS NOT NULL 
  AND t.rating_comment != ''
  AND ($1::uuid IS NULL OR t.assignee_user_id = $1)
  AND ($2::uuid IS NULL OR t.reporter_user_id = $2)
ORDER BY t.rated_at DESC
LIMIT 50
`

type GetRecentCSATCommentsParams struct {
	AssigneeUserID uuid.NullUUID `json:"assignee_user_id"`
	ReporterUserID uuid.NullUUID `json:"reporter_user_id"`
}

type GetRecentCSATCommentsRow struct {
	ID            uuid.UUID      `json:"id"`
	Rating        int32          `json:"rating"`
	RatingComment string         `json:"rating_comment"`
	RatedAt       sql.NullTime   `json:"rated_at"`
	AssigneeName  sql.NullString `json:"assignee_name"`
}

func (q *Queries) GetRecentCSATComments(ctx context.Context, arg GetRecentCSATCommentsParams) ([]GetRecentCSATCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentCSATComments, arg.AssigneeUserID, arg.ReporterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentCSATCommentsRow
	for rows.Next() {
		var i GetRecentCSATCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
