// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: roles.sql

package dbgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (name, description, permissions, is_system, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRoleParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Permissions []string  `json:"permissions"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole,
		arg.Name,
		arg.Description,
		pq.Array(arg.Permissions),
		arg.IsSystem,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE name = $1 AND is_system = false
`

func (q *Queries) DeleteRole(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRole, name)
	return err
}

const getRole = `-- name: GetRole :one
SELECT name, description, permissions, is_system, created_at, updated_at FROM roles
WHERE name = $1
`

func (q *Queries) GetRole(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, name)
	var i Role
	err := row.Scan(
		&i.Name,
		&i.Description,
		pq.Array(&i.Permissions),
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT name, description, permissions, is_system, created_at, updated_at FROM roles
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			pq.Array(&i.Permissions),
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles
SET description = $2, permissions = $3, updated_at = $4
WHERE name = $1 AND is_system = false
`

type UpdateRoleParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Permissions []string  `json:"permissions"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole,
		arg.Name,
		arg.Description,
		pq.Array(arg.Permissions),
		arg.UpdatedAt,
	)
	return err
}
