// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tickets.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachments (id, ticket_id, filename, mime_type, size_bytes, storage_path, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAttachmentParams struct {
	ID          uuid.UUID `json:"id"`
	TicketID    uuid.UUID `json:"ticket_id"`
	Filename    string    `json:"filename"`
	MimeType    string    `json:"mime_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StoragePath string    `json:"storage_path"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.ID,
		arg.TicketID,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StoragePath,
		arg.CreatedAt,
	)
	return err
}

const createReply = `-- name: CreateReply :exec
INSERT INTO ticket_replies (id, ticket_id, author_id, guest_token, body, internal, notify_customer, created_at, source, external_message_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateReplyParams struct {
	ID                uuid.UUID      `json:"id"`
	TicketID          uuid.UUID      `json:"ticket_id"`
	AuthorID          uuid.NullUUID  `json:"author_id"`
	GuestToken        sql.NullString `json:"guest_token"`
	Body              string         `json:"body"`
	Internal          bool           `json:"internal"`
	NotifyCustomer    bool           `json:"notify_customer"`
	CreatedAt         time.Time      `json:"created_at"`
	Source            string         `json:"source"`
	ExternalMessageID sql.NullString `json:"external_message_id"`
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) error {
	_, err := q.db.ExecContext(ctx, createReply,
		arg.ID,
		arg.TicketID,
		arg.AuthorID,
		arg.GuestToken,
		arg.Body,
		arg.Internal,
		arg.NotifyCustomer,
		arg.CreatedAt,
		arg.Source,
		arg.ExternalMessageID,
	)
	return err
}

const createTicket = `-- name: CreateTicket :exec
INSERT INTO tickets (
    id, tracking_number, subject, description,
    category_id, type_id, item_id, priority, status_id,
    assignee_user_id, assignee_group_id, reporter_user_id, guest_email,
    guest_name, guest_phone, ticket_type,
    created_at, updated_at, source, whatsapp_phone
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
`

type CreateTicketParams struct {
	ID              uuid.UUID      `json:"id"`
	TrackingNumber  string         `json:"tracking_number"`
	Subject         string         `json:"subject"`
	Description     string         `json:"description"`
	CategoryID      uuid.UUID      `json:"category_id"`
	TypeID          uuid.NullUUID  `json:"type_id"`
	ItemID          uuid.NullUUID  `json:"item_id"`
	Priority        string         `json:"priority"`
	StatusID        uuid.UUID      `json:"status_id"`
	AssigneeUserID  uuid.NullUUID  `json:"assignee_user_id"`
	AssigneeGroupID uuid.NullUUID  `json:"assignee_group_id"`
	ReporterUserID  uuid.NullUUID  `json:"reporter_user_id"`
	GuestEmail      sql.NullString `json:"guest_email"`
	GuestName       string         `json:"guest_name"`
	GuestPhone      string         `json:"guest_phone"`
	TicketType      sql.NullString `json:"ticket_type"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	Source          string         `json:"source"`
	WhatsappPhone   sql.NullString `json:"whatsapp_phone"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) error {
	_, err := q.db.ExecContext(ctx, createTicket,
		arg.ID,
		arg.TrackingNumber,
		arg.Subject,
		arg.Description,
		arg.CategoryID,
		arg.TypeID,
		arg.ItemID,
		arg.Priority,
		arg.StatusID,
		arg.AssigneeUserID,
		arg.AssigneeGroupID,
		arg.ReporterUserID,
		arg.GuestEmail,
		arg.GuestName,
		arg.GuestPhone,
		arg.TicketType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Source,
		arg.WhatsappPhone,
	)
	return err
}

const createTicketLink = `-- name: CreateTicketLink :exec
INSERT INTO ticket_links (source_ticket_id, target_ticket_id, link_type)
VALUES ($1, $2, $3)
`

type CreateTicketLinkParams struct {
	SourceTicketID uuid.UUID `json:"source_ticket_id"`
	TargetTicketID uuid.UUID `json:"target_ticket_id"`
	LinkType       string    `json:"link_type"`
}

func (q *Queries) CreateTicketLink(ctx context.Context, arg CreateTicketLinkParams) error {
	_, err := q.db.ExecContext(ctx, createTicketLink, arg.SourceTicketID, arg.TargetTicketID, arg.LinkType)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, id)
	return err
}

const deleteTicketLink = `-- name: DeleteTicketLink :exec
DELETE FROM ticket_links
WHERE source_ticket_id = $1 AND target_ticket_id = $2 AND link_type = $3
`

type DeleteTicketLinkParams struct {
	SourceTicketID uuid.UUID `json:"source_ticket_id"`
	TargetTicketID uuid.UUID `json:"target_ticket_id"`
	LinkType       string    `json:"link_type"`
}

func (q *Queries) DeleteTicketLink(ctx context.Context, arg DeleteTicketLinkParams) error {
	_, err := q.db.ExecContext(ctx, deleteTicketLink, arg.SourceTicketID, arg.TargetTicketID, arg.LinkType)
	return err
}

const getActiveTicketByWhatsApp = `-- name: GetActiveTicketByWhatsApp :one
SELECT t.id, t.tracking_number, t.subject, t.description, t.category_id, t.type_id, t.item_id, t.priority, t.status_id, t.assignee_user_id, t.assignee_group_id, t.reporter_user_id, t.guest_email, t.resolution_notes, t.resolved_at, t.closed_at, t.created_at, t.updated_at, t.guest_name, t.guest_phone, t.tsv, t.ticket_type, t.rating, t.rating_comment, t.rated_at, t.source, t.whatsapp_phone
FROM tickets t
JOIN statuses s ON t.status_id = s.id
WHERE t.whatsapp_phone = $1
  AND s.name NOT IN ('Resolved', 'Closed')
ORDER BY t.created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveTicketByWhatsApp(ctx context.Context, whatsappPhone sql.NullString) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getActiveTicketByWhatsApp, whatsappPhone)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.Subject,
		&i.Description,
		&i.CategoryID,
		&i.TypeID,
		&i.ItemID,
		&i.Priority,
		&i.StatusID,
		&i.AssigneeUserID,
		&i.AssigneeGroupID,
		&i.ReporterUserID,
		&i.GuestEmail,
		&i.ResolutionNotes,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestName,
		&i.GuestPhone,
		&i.Tsv,
		&i.TicketType,
		&i.Rating,
		&i.RatingComment,
		&i.RatedAt,
		&i.Source,
		&i.WhatsappPhone,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, ticket_id, filename, mime_type, size_bytes, storage_path, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const getReplyByExternalID = `-- name: GetReplyByExternalID :one
SELECT id, ticket_id, author_id, guest_token, body, internal, created_at, notify_customer, source, external_message_id FROM ticket_replies WHERE external_message_id = $1
`

func (q *Queries) GetReplyByExternalID(ctx context.Context, externalMessageID sql.NullString) (TicketReply, error) {
	row := q.db.QueryRowContext(ctx, getReplyByExternalID, externalMessageID)
	var i TicketReply
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.GuestToken,
		&i.Body,
		&i.Internal,
		&i.CreatedAt,
		&i.NotifyCustomer,
		&i.Source,
		&i.ExternalMessageID,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.Subject,
		&i.Description,
		&i.CategoryID,
		&i.TypeID,
		&i.ItemID,
		&i.Priority,
		&i.StatusID,
		&i.AssigneeUserID,
		&i.AssigneeGroupID,
		&i.ReporterUserID,
		&i.GuestEmail,
		&i.ResolutionNotes,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestName,
		&i.GuestPhone,
		&i.Tsv,
		&i.TicketType,
		&i.Rating,
		&i.RatingComment,
		&i.RatedAt,
		&i.Source,
		&i.WhatsappPhone,
	)
	return i, err
}

const getTicketByTrackingNumber = `-- name: GetTicketByTrackingNumber :one
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets WHERE tracking_number = $1
`

func (q *Queries) GetTicketByTrackingNumber(ctx context.Context, trackingNumber string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByTrackingNumber, trackingNumber)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.Subject,
		&i.Description,
		&i.CategoryID,
		&i.TypeID,
		&i.ItemID,
		&i.Priority,
		&i.StatusID,
		&i.AssigneeUserID,
		&i.AssigneeGroupID,
		&i.ReporterUserID,
		&i.GuestEmail,
		&i.ResolutionNotes,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestName,
		&i.GuestPhone,
		&i.Tsv,
		&i.TicketType,
		&i.Rating,
		&i.RatingComment,
		&i.RatedAt,
		&i.Source,
		&i.WhatsappPhone,
	)
	return i, err
}

const listAllTickets = `-- name: ListAllTickets :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllTicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listAllTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, ticket_id, filename, mime_type, size_bytes, storage_path, created_at FROM attachments WHERE ticket_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListAttachments(ctx context.Context, ticketID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT r.id, r.ticket_id, r.author_id, r.guest_token, r.body, r.internal, r.created_at, r.notify_customer, r.source, r.external_message_id, u.display_name AS author_name
FROM ticket_replies r
LEFT JOIN users u ON r.author_id = u.id
WHERE r.ticket_id = $1
ORDER BY r.created_at ASC
`

type ListRepliesRow struct {
	ID                uuid.UUID      `json:"id"`
	TicketID          uuid.UUID      `json:"ticket_id"`
	AuthorID          uuid.NullUUID  `json:"author_id"`
	GuestToken        sql.NullString `json:"guest_token"`
	Body              string         `json:"body"`
	Internal          bool           `json:"internal"`
	CreatedAt         time.Time      `json:"created_at"`
	NotifyCustomer    bool           `json:"notify_customer"`
	Source            string         `json:"source"`
	ExternalMessageID sql.NullString `json:"external_message_id"`
	AuthorName        sql.NullString `json:"author_name"`
}

func (q *Queries) ListReplies(ctx context.Context, ticketID uuid.UUID) ([]ListRepliesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReplies, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesRow
	for rows.Next() {
		var i ListRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorID,
			&i.GuestToken,
			&i.Body,
			&i.Internal,
			&i.CreatedAt,
			&i.NotifyCustomer,
			&i.Source,
			&i.ExternalMessageID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedTicketsBefore = `-- name: ListResolvedTicketsBefore :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets
WHERE resolved_at IS NOT NULL AND resolved_at < $1 AND closed_at IS NULL
ORDER BY resolved_at ASC
LIMIT $2
`

type ListResolvedTicketsBeforeParams struct {
	ResolvedAt sql.NullTime `json:"resolved_at"`
	Limit      int32        `json:"limit"`
}

func (q *Queries) ListResolvedTicketsBefore(ctx context.Context, arg ListResolvedTicketsBeforeParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listResolvedTicketsBefore, arg.ResolvedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLinks = `-- name: ListTicketLinks :many
SELECT source_ticket_id, target_ticket_id, link_type FROM ticket_links
WHERE source_ticket_id = $1 OR target_ticket_id = $1
`

func (q *Queries) ListTicketLinks(ctx context.Context, sourceTicketID uuid.UUID) ([]TicketLink, error) {
	rows, err := q.db.QueryContext(ctx, listTicketLinks, sourceTicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketLink
	for rows.Next() {
		var i TicketLink
		if err := rows.Scan(&i.SourceTicketID, &i.TargetTicketID, &i.LinkType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByAssigneeGroup = `-- name: ListTicketsByAssigneeGroup :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets WHERE assignee_group_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTicketsByAssigneeGroupParams struct {
	AssigneeGroupID uuid.NullUUID `json:"assignee_group_id"`
	Limit           int32         `json:"limit"`
	Offset          int32         `json:"offset"`
}

func (q *Queries) ListTicketsByAssigneeGroup(ctx context.Context, arg ListTicketsByAssigneeGroupParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByAssigneeGroup, arg.AssigneeGroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByAssigneeUser = `-- name: ListTicketsByAssigneeUser :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets WHERE assignee_user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTicketsByAssigneeUserParams struct {
	AssigneeUserID uuid.NullUUID `json:"assignee_user_id"`
	Limit          int32         `json:"limit"`
	Offset         int32         `json:"offset"`
}

func (q *Queries) ListTicketsByAssigneeUser(ctx context.Context, arg ListTicketsByAssigneeUserParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByAssigneeUser, arg.AssigneeUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByReporter = `-- name: ListTicketsByReporter :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets WHERE reporter_user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTicketsByReporterParams struct {
	ReporterUserID uuid.NullUUID `json:"reporter_user_id"`
	Limit          int32         `json:"limit"`
	Offset         int32         `json:"offset"`
}

func (q *Queries) ListTicketsByReporter(ctx context.Context, arg ListTicketsByReporterParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByReporter, arg.ReporterUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByStatus = `-- name: ListTicketsByStatus :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets WHERE status_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTicketsByStatusParams struct {
	StatusID uuid.UUID `json:"status_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTicketsByStatus(ctx context.Context, arg ListTicketsByStatusParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByStatus, arg.StatusID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedTickets = `-- name: ListUnassignedTickets :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets
WHERE assignee_user_id IS NULL AND assignee_group_id IS NULL
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUnassignedTicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUnassignedTickets(ctx context.Context, arg ListUnassignedTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listUnassignedTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTicketSeq = `-- name: NextTicketSeq :one
SELECT nextval('ticket_seq')::bigint
`

func (q *Queries) NextTicketSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextTicketSeq)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const searchAllTickets = `-- name: SearchAllTickets :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets
WHERE (tracking_number ILIKE $3 OR tsv @@ websearch_to_tsquery('simple', $3))
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type SearchAllTicketsParams struct {
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
	TrackingNumber string `json:"tracking_number"`
}

func (q *Queries) SearchAllTickets(ctx context.Context, arg SearchAllTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, searchAllTickets, arg.Limit, arg.Offset, arg.TrackingNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTicketsByAssigneeGroup = `-- name: SearchTicketsByAssigneeGroup :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets
WHERE assignee_group_id = $1
  AND (tracking_number ILIKE $4 OR tsv @@ websearch_to_tsquery('simple', $4))
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type SearchTicketsByAssigneeGroupParams struct {
	AssigneeGroupID uuid.NullUUID `json:"assignee_group_id"`
	Limit           int32         `json:"limit"`
	Offset          int32         `json:"offset"`
	TrackingNumber  string        `json:"tracking_number"`
}

func (q *Queries) SearchTicketsByAssigneeGroup(ctx context.Context, arg SearchTicketsByAssigneeGroupParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, searchTicketsByAssigneeGroup,
		arg.AssigneeGroupID,
		arg.Limit,
		arg.Offset,
		arg.TrackingNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTicketsByAssigneeUser = `-- name: SearchTicketsByAssigneeUser :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets
WHERE assignee_user_id = $1
  AND (tracking_number ILIKE $4 OR tsv @@ websearch_to_tsquery('simple', $4))
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type SearchTicketsByAssigneeUserParams struct {
	AssigneeUserID uuid.NullUUID `json:"assignee_user_id"`
	Limit          int32         `json:"limit"`
	Offset         int32         `json:"offset"`
	TrackingNumber string        `json:"tracking_number"`
}

func (q *Queries) SearchTicketsByAssigneeUser(ctx context.Context, arg SearchTicketsByAssigneeUserParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, searchTicketsByAssigneeUser,
		arg.AssigneeUserID,
		arg.Limit,
		arg.Offset,
		arg.TrackingNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTicketsByReporter = `-- name: SearchTicketsByReporter :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets
WHERE reporter_user_id = $1
  AND (tracking_number ILIKE $4 OR tsv @@ websearch_to_tsquery('simple', $4))
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type SearchTicketsByReporterParams struct {
	ReporterUserID uuid.NullUUID `json:"reporter_user_id"`
	Limit          int32         `json:"limit"`
	Offset         int32         `json:"offset"`
	TrackingNumber string        `json:"tracking_number"`
}

func (q *Queries) SearchTicketsByReporter(ctx context.Context, arg SearchTicketsByReporterParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, searchTicketsByReporter,
		arg.ReporterUserID,
		arg.Limit,
		arg.Offset,
		arg.TrackingNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUnassignedTickets = `-- name: SearchUnassignedTickets :many
SELECT id, tracking_number, subject, description, category_id, type_id, item_id, priority, status_id, assignee_user_id, assignee_group_id, reporter_user_id, guest_email, resolution_notes, resolved_at, closed_at, created_at, updated_at, guest_name, guest_phone, tsv, ticket_type, rating, rating_comment, rated_at, source, whatsapp_phone FROM tickets
WHERE assignee_user_id IS NULL AND assignee_group_id IS NULL
  AND (tracking_number ILIKE $3 OR tsv @@ websearch_to_tsquery('simple', $3))
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type SearchUnassignedTicketsParams struct {
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
	TrackingNumber string `json:"tracking_number"`
}

func (q *Queries) SearchUnassignedTickets(ctx context.Context, arg SearchUnassignedTicketsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, searchUnassignedTickets, arg.Limit, arg.Offset, arg.TrackingNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TrackingNumber,
			&i.Subject,
			&i.Description,
			&i.CategoryID,
			&i.TypeID,
			&i.ItemID,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeUserID,
			&i.AssigneeGroupID,
			&i.ReporterUserID,
			&i.GuestEmail,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.Tsv,
			&i.TicketType,
			&i.Rating,
			&i.RatingComment,
			&i.RatedAt,
			&i.Source,
			&i.WhatsappPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :exec
UPDATE tickets
SET subject = $2, description = $3, type_id = $4, item_id = $5,
    priority = $6, status_id = $7, assignee_user_id = $8, assignee_group_id = $9,
    resolution_notes = $10, resolved_at = $11, closed_at = $12, ticket_type = $13, updated_at = $14
WHERE id = $1
`

type UpdateTicketParams struct {
	ID              uuid.UUID      `json:"id"`
	Subject         string         `json:"subject"`
	Description     string         `json:"description"`
	TypeID          uuid.NullUUID  `json:"type_id"`
	ItemID          uuid.NullUUID  `json:"item_id"`
	Priority        string         `json:"priority"`
	StatusID        uuid.UUID      `json:"status_id"`
	AssigneeUserID  uuid.NullUUID  `json:"assignee_user_id"`
	AssigneeGroupID uuid.NullUUID  `json:"assignee_group_id"`
	ResolutionNotes sql.NullString `json:"resolution_notes"`
	ResolvedAt      sql.NullTime   `json:"resolved_at"`
	ClosedAt        sql.NullTime   `json:"closed_at"`
	TicketType      sql.NullString `json:"ticket_type"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) error {
	_, err := q.db.ExecContext(ctx, updateTicket,
		arg.ID,
		arg.Subject,
		arg.Description,
		arg.TypeID,
		arg.ItemID,
		arg.Priority,
		arg.StatusID,
		arg.AssigneeUserID,
		arg.AssigneeGroupID,
		arg.ResolutionNotes,
		arg.ResolvedAt,
		arg.ClosedAt,
		arg.TicketType,
		arg.UpdatedAt,
	)
	return err
}

const updateTicketCTI = `-- name: UpdateTicketCTI :exec
UPDATE tickets
SET category_id = $2, type_id = $3, item_id = $4, updated_at = $5
WHERE id = $1
`

type UpdateTicketCTIParams struct {
	ID         uuid.UUID     `json:"id"`
	CategoryID uuid.UUID     `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
	ItemID     uuid.NullUUID `json:"item_id"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

func (q *Queries) UpdateTicketCTI(ctx context.Context, arg UpdateTicketCTIParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketCTI,
		arg.ID,
		arg.CategoryID,
		arg.TypeID,
		arg.ItemID,
		arg.UpdatedAt,
	)
	return err
}

const updateTicketRating = `-- name: UpdateTicketRating :exec
UPDATE tickets
SET rating = $2, rating_comment = $3, rated_at = $4
WHERE id = $1
`

type UpdateTicketRatingParams struct {
	ID            uuid.UUID      `json:"id"`
	Rating        sql.NullInt32  `json:"rating"`
	RatingComment sql.NullString `json:"rating_comment"`
	RatedAt       sql.NullTime   `json:"rated_at"`
}

func (q *Queries) UpdateTicketRating(ctx context.Context, arg UpdateTicketRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketRating,
		arg.ID,
		arg.Rating,
		arg.RatingComment,
		arg.RatedAt,
	)
	return err
}
