// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: whatsapp_sessions.sql

package dbgen

import (
	"context"
)

const createWhatsAppSession = `-- name: CreateWhatsAppSession :exec
INSERT INTO whatsapp_sessions (phone, initial_message, media_url, mime_type, created_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (phone) DO UPDATE SET 
    initial_message = EXCLUDED.initial_message, 
    media_url = EXCLUDED.media_url,
    mime_type = EXCLUDED.mime_type,
    created_at = NOW()
`

type CreateWhatsAppSessionParams struct {
	Phone          string `json:"phone"`
	InitialMessage string `json:"initial_message"`
	MediaUrl       string `json:"media_url"`
	MimeType       string `json:"mime_type"`
}

func (q *Queries) CreateWhatsAppSession(ctx context.Context, arg CreateWhatsAppSessionParams) error {
	_, err := q.db.ExecContext(ctx, createWhatsAppSession,
		arg.Phone,
		arg.InitialMessage,
		arg.MediaUrl,
		arg.MimeType,
	)
	return err
}

const deleteWhatsAppSession = `-- name: DeleteWhatsAppSession :exec
DELETE FROM whatsapp_sessions
WHERE phone = $1
`

func (q *Queries) DeleteWhatsAppSession(ctx context.Context, phone string) error {
	_, err := q.db.ExecContext(ctx, deleteWhatsAppSession, phone)
	return err
}

const getWhatsAppSession = `-- name: GetWhatsAppSession :one
SELECT initial_message, media_url, mime_type FROM whatsapp_sessions
WHERE phone = $1
`

type GetWhatsAppSessionRow struct {
	InitialMessage string `json:"initial_message"`
	MediaUrl       string `json:"media_url"`
	MimeType       string `json:"mime_type"`
}

func (q *Queries) GetWhatsAppSession(ctx context.Context, phone string) (GetWhatsAppSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getWhatsAppSession, phone)
	var i GetWhatsAppSessionRow
	err := row.Scan(&i.InitialMessage, &i.MediaUrl, &i.MimeType)
	return i, err
}
